--- #YAML:1.0
name: XML-SAX-Builder
version: 0.02
license: perl
distribution_type: module
requires:
  Test::More: 0
  XML::NamespaceSupport: 0
  XML::SAX::Writer: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  XML::SAX::Builder:
    file: lib/XML/SAX/Builder.pm
    version: 0.02
  XML::SAX::Builder::ProcessingInstruction:
    file: lib/XML/SAX/Builder.pm
    version: ~
generated_by: Module::Build version 0.18
